### PR TITLE
POSIXify

### PR DESCRIPTION
**Pull request by meeDamian**
Make the script POSIX, and make the linter happy :).

---
This change is [Reviewable](https://reviewable.io/reviews/lukechilds/autoscale-do-block-storage/2)

### CODE REVIEW

**Comment by lukechilds** [comment]
Thanks for this @meeDamian, lots of good changes and improvements in here.

However I'm not sure POSIX compliance is a good idea. Why is it you want POSIX compliance over strictly requiring Bash?

Some reasons why I don't think POSIX compliance is a good idea:
- Often people actually want shell portability, which isn't necessarily the same thing as POSIX compliance
- Reliably testing POSIX compliance is not that simple
- It adds maintainer burden going forward, adding new features and merging PRs become more complicated
- Not being able to rely on modern shell features increases code complexity and reduces readability

I've worked on some large projects before that have aimed for POSIX compliance and it seemed more trouble than it was worth.

I personally think a much better approach is to aim for a single target you can reliably test against that will be available on most machines (Bash is a good candidate).

If there is a specific shell you have in mind that you want to add support for then I'd be more open to making any modifications required to get this script working in Bash + your shell if the changes aren't too invasive.

What are your thoughts?

**Comment by meeDamian** [comment]
I very much agree on most stuff :).

I guess my description didn't really _describe_ intent that well…  Which was:

* Remove any-shell-specific things (ex. `$SECONDS` -> `$(date +%s)`)
* Simplify (ex. `jq` interactions)
* Address possible pitfalls (ex. `read -r`, wrap stuff in `"` to prevent accidental word-splitting)
* Add support for formats `--flag=val` & `--flag val`

All that trying to either make things simpler, or at least not make them more difficult 😬.

Anything got harder to follow, you reckon?

**Comment by lukechilds** [comment]
Ok, I would say:

>- Remove any-shell-specific things (ex. $SECONDS -> $(date +%s))

Why do you think that is better? IMO targeting one specific shell is a good thing. We know `$SECONDS` is always gonna be there if we target Bash. It makes the script portable to any system that runs Bash.

If you depend on the `date` binary that's less portable. What if you run the script on a system where `date` is missing, not currently in the `$PATH`, or it's some weird version that doesn't support the exact same flags? It could fail in unpredictable ways.

>- Simplify (ex. jq interactions)
>- Address possible pitfalls (ex. read -r, wrap stuff in " to prevent accidental word-splitting)

👌

>Add support for formats --flag=val & --flag val

I'm not sure this is a good idea. I wouldn't mind so much if this was a proper language where this could be done more easily or if it could be handed off to an existing module. But considering it's Bash I don't think it's worth the effort of rolling our own (potentially broken) solution when we could just enforce a specific pattern with much simpler code.

For example I've already found a situation where the two formats behave differently:

```
$ ./checkvolumesize --token stringwith=symbol
TOKEN=stringwith=symbol

$ ./checkvolumesize --token=stringwith=symbol
TOKEN=stringwith
```

It seems like to correctly handle this and all edge cases in Bash could be quite a lot of work.

>Anything got harder to follow, you reckon?

Option parsing seems a bit more complex.

Also string substitution is a bit harder to follow IMO, for example this is not that intuitive:

```bash
method="${post_data:+POST}"
method="${method:-GET}"
```

However it's very obvious what this is doing, it's basically english:

```bash
method="GET"
if [[ $post_data ]]; then
  method="POST"
fi
```

**Comment by meeDamian** [comment]
I fixed the `=` case, but other than that I hear ya ^^.

I guess it can be closed, as you really want `bash`, and it's not on most systems I use 🤷🏻‍♂️. `(da|a|z|fi)sh` FTW!

**Pull request closed without merging**
